[package]
name = "idm-tools"
version = "0.1.0"
edition = "2021"
authors = ["Risto Saarelma <risto.saarelma@iki.fi>"]
description = "Implicit Data Markup utilities"
homepage = "https://github.com/rsaarelm/idm-tools"
repository = "https://github.com/rsaarelm/idm-tools"
license = "MIT/Apache-2.0"
resolver = "2"

[dependencies]
idm = "0.4"
